// Code generated by protoc-gen-go-kirito. DO NOT EDIT.
// versions:
// - protoc-gen-go-kirito v0.0.1
// source: api/user/user.proto

package user

import (
	context "context"
	application "github.com/go-kirito/pkg/application"
)

// IUserUseCase is the server API for User service.
// for forward compatibility
type IUserUseCase interface {
	UserLogin(context.Context, *LoginRequest) (*LoginReply, error)
	UserRegister(context.Context, *RegisterRequest) (*RegisterReply, error)
	UserCode(context.Context, *UserCodeRequest) (*UserCodeReply, error)
}

// @di di文件根据注解自动生成
func RegisterUserServer(app application.Application, srv IUserUseCase) {
	if app.HttpServer() != nil {
		RegisterUserHTTPServer(app.HttpServer(), srv)
	}
	if app.GrpcServer() != nil {
		RegisterUserGrpcServer(app.GrpcServer(), srv)
	}
}
