// Code generated by protoc-gen-go-kirito. DO NOT EDIT.
//go:build wireinject
// +build wireinject

package di

import (
	user0 "my_sso/api/user"

	service_0 "my_sso/internal/user/domain/service"
	repository_0 "my_sso/internal/user/repository"
	usecase_0 "my_sso/internal/user/usecase"

	"github.com/go-kirito/pkg/application"
	"github.com/google/wire"
)

type UseCases struct {
	iuserusecase0 user0.IUserUseCase
}

func RegisterService(app application.Application) error {
	uc, err := MakeUseCase()
	if err != nil {
		return err
	}

	user0.RegisterUserServer(app, uc.iuserusecase0)
	return nil
}

func MakeUseCase() (*UseCases, error) {
	panic(wire.Build(
		wire.Struct(new(UseCases), "*"),

		repository_0.NewUserRepo,
		repository_0.NewUserCacheRepo,
		usecase_0.NewUserUseCase,
		service_0.NewUserService,
	))
}
