// Code generated by protoc-gen-go-kirito. DO NOT EDIT.
//go:build wireinject
// +build wireinject

package di

import (
	login0 "login_registration/api/login"

	usecase_0 "login_registration/internal/login_registration/usecase"

	"github.com/go-kirito/pkg/application"
	"github.com/google/wire"
)

type UseCases struct {
	iloginusecase0 login0.ILoginUseCase
}

func RegisterService(app application.Application) error {
	uc, err := MakeUseCase()
	if err != nil {
		return err
	}

	login0.RegisterLoginServer(app, uc.iloginusecase0)
	return nil
}

func MakeUseCase() (*UseCases, error) {
	panic(wire.Build(
		wire.Struct(new(UseCases), "*"),

		usecase_0.NewLoginUseCase,
	))
}
