// Code generated by protoc-gen-go-kirito. DO NOT EDIT.
// versions:
// - protoc-gen-go-kirito v0.0.1
// source: api/login/login.proto

package login

import (
	context "context"
	application "github.com/go-kirito/pkg/application"
)

// ILoginUseCase is the server API for Login service.
// for forward compatibility
type ILoginUseCase interface {
	CreateLogin(context.Context, *CreateLoginRequest) (*CreateLoginReply, error)
	UpdateLogin(context.Context, *UpdateLoginRequest) (*UpdateLoginReply, error)
	DeleteLogin(context.Context, *DeleteLoginRequest) (*DeleteLoginReply, error)
	GetLogin(context.Context, *GetLoginRequest) (*GetLoginReply, error)
	ListLogin(context.Context, *ListLoginRequest) (*ListLoginReply, error)
}

// @di di文件根据注解自动生成
func RegisterLoginServer(app application.Application, srv ILoginUseCase) {
	if app.HttpServer() != nil {
		RegisterLoginHTTPServer(app.HttpServer(), srv)
	}
	if app.GrpcServer() != nil {
		RegisterLoginGrpcServer(app.GrpcServer(), srv)
	}
}
