// Code generated by Kirito. DO NOT EDIT.
package model

type Device struct {
	Id     uint64 `gorm:"column:id;primary_key;AUTO_INCREMENT"` // 主键
	Uid    uint64 `gorm:"column:uid;default:0;NOT NULL"`        // 用户主键
	Client string `gorm:"column:client;NOT NULL"`               // 客户端
	Model  string `gorm:"column:model;NOT NULL"`                // 设备型号
	Ip     uint32 `gorm:"column:ip;default:0;NOT NULL"`         // ip地址
	Ext    string `gorm:"column:ext;NOT NULL"`                  // 扩展信息
	Ctime  uint32 `gorm:"column:ctime;default:0;NOT NULL"`      // 注册时间
}

func (m *Device) TableName() string {
	return "device"
}
