// Code generated by Kirito. DO NOT EDIT.
package model

type Trace struct {
	Id    uint64 `gorm:"column:id;primary_key;AUTO_INCREMENT"` // 主键
	Uid   uint64 `gorm:"column:uid;default:0;NOT NULL"`        // 用户主键
	Type  int8   `gorm:"column:type;default:0;NOT NULL"`       // 类型(0:注册1::登录2:退出3:修改4:删除)
	Ip    uint32 `gorm:"column:ip;NOT NULL"`                   // ip
	Ext   string `gorm:"column:ext;NOT NULL"`                  // 扩展字段
	Ctime uint32 `gorm:"column:ctime;default:0;NOT NULL"`      // 注册时间
}

func (m *Trace) TableName() string {
	return "trace"
}
