// Code generated by Kirito. DO NOT EDIT.
package model

import (
	"time"
)

type Users struct {
	Id     uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT"`            // 主键
	Name   string    `gorm:"column:name;NOT NULL"`                            // 用户名
	Email  string    `gorm:"column:email;NOT NULL"`                           // 邮箱
	Mobile string    `gorm:"column:mobile;NOT NULL"`                          // 手机号
	Passwd string    `gorm:"column:passwd;NOT NULL"`                          // 密码
	Salt   string    `gorm:"column:salt;NOT NULL"`                            // 盐值
	Ext    string    `gorm:"column:ext;NOT NULL"`                             // 扩展字段
	Status int8      `gorm:"column:status;default:0;NOT NULL"`                // 状态（0：未审核,1:通过 10删除）
	Ctime  uint32    `gorm:"column:ctime;default:0;NOT NULL"`                 // 创建时间
	Mtime  time.Time `gorm:"column:mtime;default:CURRENT_TIMESTAMP;NOT NULL"` // 修改时间
}
